config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :users
  resources :articles do
    resources :comments
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord

  validates_uniqueness_of :username
  validates_presence_of :username
  validates_length_of :username, :minimum => 5, :maximum => 50
  validates_length_of :password, :in => 6..20
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => "Incorrect email format"
  validates_presence_of :status
  validates_inclusion_of :status, :in => 0..1, # %w{ 0 1 }
                         :message => "should be '0' -> (NG) or '1' -> (OK)"

  self.table_name = "users"
  self.primary_key = "id"

  validates :username, presence: true, length: { minimum: 5 }
  validates :password, presence: true, length: { minimum: 6 }
  validates :email, presence: true, length: { minimum: 5 }
  validates :version, presence: true,if: :fun_update_version_is_same?

  before_save :fun_create_on
  before_update :fun_update_on

  protected
  def fun_update_version_is_same?

    if version != self.version
      errors.add(:version, "version " + version.to_s + " not " + self.version.to_s)
      return
    end

  end

  def fun_update_on
    # self.update_on = DateTime.parse(Time.now.strftime('%Y-%m-%d %H:%M:%S.%N').to_s
    self.update_on = Time.now.strftime('%Y-%m-%d %H:%M:%S.%N')
    self.version = self.version + 1
  end

  protected
  def fun_create_on

    unless create_on
      #self.create_on = DateTime.parse(Time.now.to_s).strftime('%Y-%m-%d %H:%M:%S.%N').to_s
      self.create_on = Time.now.strftime('%Y-%m-%d %H:%M:%S.%N')
      self.version = 1
      self.status = 1
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "123456", except: [:index, :show]

  def new
    @article = Article.new
  end
  
  def create
    # render plain: params[:article].inspect

    @article = Article.new(article_params_new)
    if @article.save
      redirect_to @article
    else
      ## render plain: format("Error save -> %s \n\n %s",
      ##                    @article.errors.inspect,
      ##                    params[:article].inspect)
      render "new"
    end


  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params_update)
      redirect_to @article
    else
      render "edit"
    end
  end


  def show
    # render plain: params[:id].inspect
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end


  private
  def article_params_new
    params.require(:article).permit(:title, :text)
  end

  private
  def article_params_update
    params.require(:article).permit(:id, :title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "123456", only: :destroy

  def new
    @comment = Comment.new
  end

  def create
    # render plain: params[:comment].inspect

    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params_new)
    redirect_to article_path(@article)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @article = Article.find(params[:article_id])
    @comment = @article.comments.update(comment_params_update)
    redirect_to article_path(@article)
  end


  def show
    # render plain: params[:id].inspect
    @comment = Comment.find(params[:id])
  end

  def index
    @comments = Comment.all
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end


  private
  def comment_params_new
    params.require(:comment).permit(:article_id, :commenter, :body)
  end

  private
  def comment_params_update
    params.require(:comment).permit(:id, :title, :text)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # new
  def new
    @user = User.new
    @user.version = 1
    @user.status = 1
  end

  # create
  def create
    # render plain: params[:user].inspect

    @user = User.new(user_params_new)
    @user.version = 1
    @user.status = 1

    if @user.save
      redirect_to @user
    else
      ## render plain: format("Error save -> %s \n\n %s",
      ##                    @user.errors.inspect,
      ##                    params[:user].inspect)
      render "new"
    end


  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params_update)
      redirect_to @user
    else
      render "edit"
    end
  end


  def show
    # render plain: params[:id].inspect
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  def find
    @user = User.new
    if params[:username]
      @user = User.find_by(name: params[:username])
    end
    redirect_to @user
  end

  private
  def user_params_new
    params.require(:user).permit(:username, :password, :email)
  end

  private
  def user_params_update
    params.require(:user).permit(:id, :username, :password, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.hidden_field :id %>
    </p>

    <p>
      <%= f.submit %>
    </p>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <% pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:</h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <p>
          <%= @article.errors.inspect %>
        </p>
    <% end %>



<% end %>

app/views/articles/edit.html.erb
<h1>New User</h1>


<%= render 'form' %>

<%= link_to 'back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing User</h1>

<%= link_to 'new', new_article_path %>

<table>
  <tr>
    <th>id</th>
    <th>title</th>
    <th>text</th>
    <th>show</th>
    <th>edit</th>
    <th>destroy</th>

  </tr>

  <% @articles.each do |article| %>
    <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'show', article_path(article) %></td>
        <td><%= link_to 'edit', edit_article_path(article) %></td>
        <td><%= link_to 'destroy', article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>

</table>

app/views/articles/new.html.erb
<h1>New Article</h1>


<%= render 'form' %>

<%= link_to 'back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit Article', edit_article_path(@article) %> |
<%= link_to 'Back to Articles', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <%= comment.id %>.
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p style="size: 5px">
  <strong>Body:</strong>
  <span style="color: gray"><%= comment.body %></span>
</p>

<p>
  <%= link_to 'Destroy Comment: ' + comment.id.to_s, [comment.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/edit.html.erb
<h1>New User</h1>


<%= render 'form' %>

<%= link_to 'back', "/user" %>

app/views/user/index.html.erb
<h1>Listing User</h1>

<table>
  <tr>
    <th>id</th>
    <th>username</th>
    <th>email</th>
    <th>show</th>
    <th>edit</th>
    <th>destroy</th>

  </tr>

  <% @users.each do |user| %>
    <tr>
        <td><%= user.id %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'show', user_path(user) %></td>
        <td><%= link_to 'edit', edit_user_path(user) %></td>
        <td><%= link_to 'destroy', user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>

</table>



<%= link_to 'new', "/user/new" %>

app/views/user/new.html.erb
<h1>New User</h1>


<%= render 'form' %>

<%= link_to 'back', "/user" %>

app/views/user/show.html.erb
<h1>Show User > <%=  @user.id %></h1>

<p>
  <strong>username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'back', "/user" %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <p>
      <%= f.label :username %><br>
      <%= f.text_field :username, :size => 20, :min => 5, :max => 30 %>
    </p>

    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password, :size => 20, :min => 6, :max => 30 %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email, :size => 20, :min => 6 %>
    </p>
    <p>
      <%= f.hidden_field :id %>
      <%= f.hidden_field :status %>
      <%= f.hidden_field :version %>
    </p>


    <p>
      <%= f.submit %>
    </p>

    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <% pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <p>
          <%= @user.errors.inspect %>
        </p>
    <% end %>



<% end %>

app/views/users/edit.html.erb
<h1>New User</h1>


<%= render 'form' %>

<%= link_to 'back', users_path %>

app/views/users/index.html.erb
<h1>Listing User</h1>

<%= link_to 'new', new_user_path %>

<table>
  <tr>
    <th>id</th>
    <th>username</th>
    <th>email</th>
    <th>show</th>
    <th>edit</th>
    <th>destroy</th>

  </tr>

  <% @users.each do |user| %>
    <tr>
        <td><%= user.id %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'show', user_path(user) %></td>
        <td><%= link_to 'edit', edit_user_path(user) %></td>
        <td><%= link_to 'destroy', user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>

</table>

app/views/users/new.html.erb
<h1>New User</h1>


<%= render 'form' %>

<%= link_to 'back', users_path %>

app/views/users/show.html.erb
<h1>Show User > <%=  @user.id %></h1>

<p>
  <strong>username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'back', users_path %>

app/views/welcome/index.html.erb
<h1>Hello world</h1>
<p>Welcome to MyRails !</p>


<p>
    <%= link_to 'List Users', controller: 'users' %>
</p>
<p>
  <%= link_to 'List Articles', controller: 'articles' %>
</p>